### ISSUE TITLE
matchers.contains(number) support

### ISSUE THREAD

**Issue by focusaurus** [testdouble/testdouble.js#102]
Given this repro snippet

    const td = require('testdouble')

    const repro = td.function()
    repro([1])
    td.verify(repro(td.matchers.contains(1)))

I'd like this to succeed, but currently it throws an exception "Error: Error: testdouble.js - td.matchers.contains - this matcher only supports strings, arrays, and plain objects"

I think to fix this is just a matter of `or _.isNumber(containing)` on https://github.com/testdouble/testdouble.js/blob/30e27f54de0e84fe99a9c33340a0474c3a21369b/src/matchers/index.coffee#L45

**Comment by searls** [comment]
Ah, the issue is that you're saying that `[1]` should contain `1`, and that doesn't make a lot of sense. Have you tried `td.verify(repro(td.matchers.contains([1])))`?

**Comment by focusaurus** [comment]
> you're saying that [1] should contain 1, and that doesn't make a lot of sense. 

It makes perfect sense to me.

Here's two examples. The ONLY difference is replacing the string `'one'` with the number `1`. I don't see any reason why both of these should not behave identically. The first one works fine, the second one throws an exception.

    const td = require('testdouble')

    const withString = td.function()
    withString(['one'])
    td.verify(withString(td.matchers.contains('one')))

    const withNumber = td.function()
    withNumber([1])
    td.verify(withNumber(td.matchers.contains(1)))

**Comment by searls** [comment]
Ugh, I really apologize. I shot from the hip and speculated when I replied above because I was on a machine without a dev environment, but now that I can test it out locally you're completely write. The truth is this feature doesn't work how I thought it did. 

I'm sort of annoyed with myself for not finding this API quirk before going 1.0, because it's not how I want it, but it's also not worth breaking backwards-compatibility. 

Naturally, this mistake means I need to accept any kind of input, including `null`/`undefined`/`true`, etc. I'll take a stab at this now.

**Comment by focusaurus** [comment]
Yeah I can give it some more thought in terms of what the ideal API/behavior would be, but I think at the moment it's not self-consistent. Could go more explicit and tighter matching or more loose and flexible matching I guess.

**Comment by searls** [comment]
Check out the update in 1.4.2 and let me know if that works for you

**Comment by focusaurus** [comment]
Yes, no more exception! Thanks for the quick fix. Been getting a lot of mileage out of testdouble recently.
