### ISSUE TITLE
td.replace breaks subsequent require calls

### ISSUE THREAD

**Issue by scottaj** [testdouble/testdouble.js#103]
This code example demonstrates the problem. Since `CantMakeHeadsOrTailsOfItError` is require'd after doing a `td.replace`, it fails the `instanceof` check in the test. 

It seems unexpected that replacing a different module would have any effect on other modules require'd after it.

To be clear either removing the td.replace, or moving the require of the error to before the td.replace fixes the issue, so it is easy to work around.

```javascript
...
const MyLib = require('../index');
const MyDependency = td.replace('../dependency');
const CantMakeHeadsOrTailsOfItError = require('../cant-make-heads-or-tails-of-it-error');

describe('My Lib', function() {
  ...
  describe('#tail', function() {
    it('throws an error if the provided object is not an array', function () {
      try {
        myLib.tail(7);
        throw new Error('Did not get expected exception.');
      } catch (error) {
        expect(error).to.be.an.instanceOf(CantMakeHeadsOrTailsOfItError);
      }
    });
  });
});
```

Here is a runnable project with the full code example and failing test from above: https://github.com/scottaj/td-instanceof-example

**Comment by searls** [comment]
There are three issues in the example above, and two of them will confound the third (which is a real issue)

1. If you're using the `td.replace` API, it needs to be inside a `beforeEach` or some kind of `before` hook that gets reset after each test, paired with `td.reset()` in an `afterEach` hook so that the state of the universe can be properly restored.

2. Any dependencies you replace need to be `td.replace()`'d before you actually call `require` on the subject under test; otherwise, the library has no way to know what dependencies to replace when the subject is loaded (and will instead load real ones). (e.g. `MyDependency = td.replace('../dependency')` should be before `MyLib = require('../index')`)

3. Instantiable function dependencies `replace()`'d with testdouble.js will fail `instanceof` checks.

Can you resolve the first two issues and retitle/redescribe the problem in those contexts? Otherwise I'll close and open a new one for it.

**Comment by scottaj** [comment]
Sure, I'll update it.

**Comment by searls** [comment]
Closing. Follow along in #107
