### ISSUE TITLE
not matcher and calling function multiple times

### ISSUE THREAD

**Issue by adamniedzielski** [testdouble/testdouble.js#122]
Thank you for the amazing library - I'm a happy user! I found one issue with how the "not" matcher behaves when the function is called multiple times. Please, take a look:

```javascript
let roll = td.function();
roll(1);
td.verify(roll(td.matchers.not(1)));
```

This works as expected - the test fails with:

```
Unsatisfied verification on test double.
            
              Wanted:
                - called with `(not(1))`.
            
              But was actually called:
                - called with `(1)`.
```

However this one does not fail the test:

```javascript
let roll = td.function();
roll(4);
roll(1);
td.verify(roll(td.matchers.not(1)));
```

I guess that the problem here is that one function call ("4") satisfies the matcher. I wonder whether the "not" matcher should mean "none of the calls equal" or "not every call equals". What do you think?

**Comment by searls** [comment]
Yeah, you diagnosed the issue you ran into here. My recommendation (since it should be unusual that a collaboration test should intentionally make a test double blow up) would be to treat the explosion as a stubbing and not a verification. 

Reason being: verifying something did not happen isn't much of a specification at all (surely there are millions of things your subject under test _doesn't_ do, but they don't all warrant an assertion)

Try this instead:

```js
let roll = td.function();
td.when(roll(1)).thenThrow(new Error('woah do not roll a 1'))

roll(1);
```

**Comment by adamniedzielski** [comment]
@searls Your reasoning makes sense. Thank you very much for the suggestion.
