### ISSUE TITLE
Add support for concurrent test runners (ava)?

### ISSUE THREAD

**Issue by paultyng** [testdouble/testdouble.js#131]
Perhaps instead of the common pattern of:

```js
afterEach(() => td.reset());
```

An additional pattern similar to:

```js
beforeEach(t => {
  t.context.td = td.scoped(); // or new TestDouble() or ...?
});

test(t => {
  const { td } = t.context;

  td.verify(...);
});
```

Could be supported?

**Comment by paultyng** [comment]
I'm not 100% sure it doesn't work, I done some small samples with testdouble and ava and didn't hit any issues but probably because my tests didn't overlap very much.  I'll have to see if I can reproduce an error in a test suite.

**Comment by searls** [comment]
Let's close for now until someone somewhere runs into a real (as opposed to speculative) problem.

**Comment by searls** [comment]
Thanks @ackerdev -- that gives me some insight to think on how (and whether) to undertake what we'd need to do to support parallel tests

**Comment by searls** [comment]
I've given more thought to this and I still don't have any good proposals. My thoughts follow.

## Global state

There are several aspects of td's API design that rely on global state:

* `td.replace(obj, 'someProp')` - which will actually replace `obj.someProp` from the time it's called to the time `td.reset()` is next invoked. If two tests run concurrently and `obj` is referenced by both, these replacements will step on one another
* `td.replace('../path/to/module')` - td's [quibble](https://github.com/testdouble/quibble) integration will intercept all calls to `require` for the given absolute module path until `reset` is called
* `td.when(myTd()).thenReturn('foo')` - configured stubbings are stored globally for a given test double function, since there's only one stubbing store, and it's keyed off the identity of test double functions.
* `td.verify(saveThing('thing'))` - recorded invocations are stored globally and are also keyed off the identity of test double functions

So the first two instances are examples of td.js mutating state of things it doesn't own, and the final two describe td.js's internal storage of the state of known test double functions. 

## What can we do?

If the question is "how do we use td.js with a concurrent test runner?", the answer must be in two parts:

1. Don't use any type of `td.replace` on modules or objects that are shared across tests. There's just no safe way to muck with global state and nothing the library can do to safeguard this
2. Sequester the config & call stores for `td.when`/`td.verify` between tests, by either:
  1. instruct users to separate test double instantiation for each test so that two test methods aren't sharing the exact same test double function; this should be default/normal practice regardless of whether you're using a concurrent runner or not (e.g. create them in a `beforeEach`, not in top-level scope or in a `before` (all))
  2. if for some reason the above isn't tenable (I can't imagine it wouldn't be), td could implement a feature akin to `sinon.sandbox()` that forked its state (e.g. `td2 = td.fork()`) to keep these things separate; I really don't think this can possibly be necessary, though, if each test is creating its own test doubles, as it should be

## Ava-specific advice

(FWIW, this [has been raised](https://github.com/avajs/ava/issues/1066) with respect to Sinon as well)

Now, one thing Ava does that is interesting is that it forks each test file into a separate operating system process. If every single _test_ were split into its own process, all these problems would go away, since there'd be a separate global state for each.

* You can use [.serial](https://github.com/avajs/ava#running-tests-serially) and make any tests using `td` run serially inside of a specific file. This won't please purists, but (a) any tests using test doubles should be _super isolated_, (b) most often ought to be able to be defined synchronously, and (c) there's no way anything like `td.replace` could conceivably work in anything but a serial context within a single process so it's an honest thing to do, even if it looks "bad"
* You could break every test into its own file, which seems like a lot to manage
* You could contribute to Ava, where a "fork per test" issue has already been discussed and de-prioritized in avajs/ava#421

I think the above Ava-specific options are all worth thinking about, but I don't think there's anything the library can do to solve the `td.replace` problem and anything it _should_ do to add sandbox/fork support, unless I'm really missing something (counter-examples welcome)

**Comment by kristianmandrup** [comment]
See https://www.npmjs.com/package/forking-tap for inspiration ;)
