### ISSUE TITLE
`td.replace()` doesn't work with `import`?

### ISSUE THREAD

**Issue by mockdeep** [testdouble/testdouble.js#147]
I've got the following code:

``` js
// test file
td.replace('_config/routes', fakeRoutes);
const router = require('router');

describe('router', function () {
  it('renders routes', function () {
    const renderedRouter = TestUtils.renderIntoDocument(router);
    ...
  });
});

// router.jsx
const routes = require('_config/routes');
module.exports = <Router history={browserHistory}>{routes}</Router>;
```

When I switch it to use `import` instead of `require` however, the dependency on `_config/routes` is no longer replaced:

``` js
// test file
td.replace('_config/routes', fakeRoutes);
import router from 'router';

describe('router', function () {
  it('renders routes', function () {
    const renderedRouter = TestUtils.renderIntoDocument(router);
    ...
  });
});

// router.jsx
const routes = require('_config/routes');
export default <Router history={browserHistory}>{routes}</Router>;
```

I get an error, which tells me that it's calling `reqwest`, which shouldn't happen if `_config/routes` is stubbed:

``` js
  1) router renders routes:
     ReferenceError: ActiveXObject is not defined
      at xhr (node_modules/reqwest/reqwest.js:77:22)
      ...
```

Is this syntax not supported by `testdouble.js`? Or am I looking in the wrong place? I'm running it through babel using `"presets": ["react", "es2015"]`, so maybe it should be transpiled to something else?

**Comment by bjarketrux** [comment]
Could it be that `import router from 'router';` is hoisted up to the top of the file?
So that the generated ES5 is:

```javascript
var router = require('router');
td.replace('_config/routes', fakeRoutes);
```

I think this was a thing recently on Meteor (using Babel i believe). What platform are you using?
Anyway, for tests we now just use`require` and in the source `import`. In this way you can also leave testing framework in the top and the file under test in a before each:

```javascript
import td from 'testdouble';
import chai from 'chai';

describe('router', function () {
  var subject;

  beforeEach(function() {
    td.replace('_config/routes', fakeRoutes);
    subject = require('router');
  });

  it('renders routes', function () {
    const renderedRouter = TestUtils.renderIntoDocument(router);
    ...
  });
});
```

**Comment by searls** [comment]
We should investigate ES `import` and what, if anything td.js can do to make this more graceful. My off-the-cuff reaction is "ugh", because `import` is statically resolved and also almost always transpiled to something that isn't actually `import` at runtime.

**Comment by mockdeep** [comment]
Thanks for the response. It definitely seems like a lot of things are in flux, so I can imagine it's pretty hard to keep up with all the different ways people want to do things.

@bjarketrux thanks for the suggestion. That seems to work with the addition of `.default`:

```js
const router = require('router').default;
```

**Comment by searls** [comment]
I've been noodling on this, and one approach might be to create a babel plugin for either test double or quibble which provides the needed hook to swap out an implementation at import-time

https://github.com/speedskater/babel-plugin-rewire

I don't love this approach because it would only work for babel, and if you're using babel then you're also boiling these imports down to common JS style requires (for now?). But this is a direction we could at least theoretically explore to make td.replace use seamless for the import statement

**Comment by mockdeep** [comment]
Hmm, yeah, that feels pretty unpleasant. I confirmed for myself that the `import`s get hoisted. This (pay special attention to the `console.log`):

```js
import React from 'react';
import {Link} from 'react-router';

console.log('above the help link import');

import HelpLink from '_common/components/help_link';
```

compiles to this:

```js
var _react = require('react');

var _react2 = _interopRequireDefault(_react);

var _reactRouter = require('react-router');

var _help_link = require('_common/components/help_link');

var _help_link2 = _interopRequireDefault(_help_link);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

console.log('above the help link import');
```

It's not much better, but is there any way to tie into `require` even earlier? Say, maybe by having a `td.instrumentRequires()` that we can call in a setup file for the tests? Maybe it's too invasive, but another option might be to do it as soon as `td` is required in...

**Comment by searls** [comment]
@mockdeep if you're curious, check out https://github.com/testdouble/quibble -- in that project we do wrap `Module.load` for the existing functionality. We could expand how it works to cover this case, though I really dislike it since it wouldn't work on "real" `import` statements, which would lead to a lot of confusion should anyone actually start using native imports.

**Comment by mockdeep** [comment]
Hmm, do any of the other libraries handle native `import`? Or do they just handle it as a babel plugin? I take it `Module.load` doesn't get used for native `import`s? Another random thought is to somehow hack `NODE_PATH`, but I don't have much of a clue how that would work...

**Comment by searls** [comment]
Since `import` is statically analyzed (for the purpose of things like tree-shaking, bundling, etc), it's hard to imagine how anything could safely intercept an import statement.

Everything I've seen either relies on babel compiling down to node-compatible commonjs modules or on providing a babel plugin.

**Comment by searls** [comment]
I'm going to close this until someone comes up with a way to "defeat" the static-ness of import when running tests—I suspect it'll never be possible, but I'm open to looking at hacks.

Anyway you should check out 1.10.0, which adds support `td.replace` for ES classes as well the `export` keyword from your source modules. The concession is that inside the test you need to use `require` so that you can put the `td.replace` calls ahead of requiring your subject, but since it's a test listing that seems like an agreeable concession.
