### ISSUE TITLE
Is testdouble.js not compatible with PhantomJS?

### ISSUE THREAD

**Issue by bjarketrux** [testdouble/testdouble.js#154]
Looks like Quibble uses an V8 specific API: https://github.com/testdouble/quibble/issues/3
When running our tests on our CI testdouble fails with
```
phantomjs: TypeError: undefined is not an object (evaluating 'e.stack[0]')
```

Anything I can do to make the CI tests work in PhantomJS?
Thanks

**Comment by searls** [comment]
Hey @bjarketrux -- `td.replace` for module paths does not work outside of Node.js, as Quibble doesn't just depend on v8, but also the internals of Node's native `Module` module. 

Forgive me, because td.replace is indeed really confusing in how many types of arguments it can receive, resulting in very different behavior, but the simple way to think of it is that anything about CommonJS-ish modules is specific to Node.js until someone thinks up a better way to automatically rewire than what quibble does.

Here are the relevant [docs](https://github.com/testdouble/testdouble.js/blob/master/docs/7-replacing-dependencies.md#nodejs) for anyone just realizing this.

Separately, @bjarketrux, if you could find the exact snippet that resulted in this error, perhaps we could throw an error message about lack of support for the environment you're in--looks like whatever I'm doing to check that we're in a Node environment is insufficient.
