### ISSUE TITLE
Matcher for a specific position

### ISSUE THREAD

**Issue by ruiquelhas** [testdouble/testdouble.js#156]
Is there a way to match arguments at a specific position, ignoring everything else that is not specified? If not, is this something that might make sense to have?

```js
const td = require('testdouble');
const foobar = td.function();

// instead of adding explicit matchers for all arguments like
td.when(foobar(td.matchers.anything(), 'bar')).thenReturn('baz');

// maybe something like the following
td.when(foobar({ position: 1, value: 'bar' })).thenReturn('baz');

foobar('foo', 'bar'); // 'baz'
```

**Comment by searls** [comment]
We don't have something like this, and while I understand and appreciate what you're describing, I wouldn't support the inclusion of an API like this for a few reasons:

* **Arguments should be ambiguous only sparingly** - td.js is designed to be used for isolated unit tests, and as a result most of the time 100% of the arguments are (directly or indirectly) controlled by the test and can be known and typed. Explicitness always trumps ambiguity in these cases. Typically, when a team is making ample use of matchers, their tests are quasi-isolated/quasi-integrated which is often a smell of mixing levels of abstraction.

* **Good methods take few arguments** - an option like this would be most useful for methods that take more than a few arguments, but good methods don't take more than a few arguments. Since the purpose of a test double library is to encourage test authors to design good dependencies for the subject under test, anything we add to the API that makes it easy to create "bad" dependencies (e.g. a function that takes 7 arguments) would be a bad idea

* **Config options for `when` and `verify` come at a high cognitive cost** - every option we add to stubbing/verifying is another thing readers of tests will have to wrap their mind around, so it's very important they be both necessary and obvious. I tried to address whether this option might be necessary above, but I feel like it wouldn't be very obvious to a reader what this configuration would be doing to a reader unaware of this feature. Stubs that work in mysterious ways is one of the leading causes of people's frustration with mocking generally, so we should be careful of exacerbating that.

**Comment by ruiquelhas** [comment]
Makes sense. Thanks!
