### ISSUE TITLE
td.verify and td.when redundency warning

### ISSUE THREAD

**Issue by LandonSchropp** [testdouble/testdouble.js#170]
I have a test suite that periodically invokes a stubbed function on an object. and consumes the result. Since that function gets reused repeatedly in my test suite, I've defined it in a before each block for all of the specs.

However, in one particular spec I want to verify the test double *wasn't* called. Unfortunately, I get a warning that both stubbing and verifying the call with the same arguments is redundant. This warning makes perfect sense, but I don't think it's applicable to situations where `times` is anything other than `1`.

Here's a simplified example:

```
describe("example", () => {
  let func;

  beforeEach(() => {
    func = td.function();
    td.when(func()).thenReturn("Nope");
  });

  it('is never called', () => {
    td.verify(func(), { times: 0 });
  });
});
```

And this is the warning:

```
Warning: testdouble.js - td.verify - test double was both stubbed and verified with arguments (), which is redundant and probably unnecessary. (see: https://github.com/testdouble/testdouble.js/blob/master/docs/B-frequently-asked-questions.md#why-shouldnt-i-call-both-tdwhen-and-tdverify-for-a-single-interaction-with-a-test-double )
```

**Comment by searls** [comment]
There's two issues at play here:

* Configuration in cascading test-styles like the nested example groups in Jasmine or Mocha mean that a generic test double configuration should be able to be made more and more specific as you get closer to a specific example. This works pretty well with stubbings, because last-in-satisfied-stubbing-wins.
* When you have a stubbing that's called under conditions `A`, `B`, and `C`, but the test author knows it won't need to be called at `D`, the question arises "what should the test do here"?

I would argue that verifying a stubbing wasn't called is _probably_ still not necessary in this case. To recap: `td.verify` should only be used if there's no way to verify the subject did something, which is typically when the test double function has a side effect and doesn't return a value. 

I'll expand your example below:

```js
describe("example", () => {
  let func;

  beforeEach(() => {
    func = td.function();
    td.when(func()).thenReturn("Nope");
  });

  it('is called when A', () => {
    var result = subject('A', func)

    expect(result).to.equal('pants')
  });

  it('is never called when B', () => {
    var result subject('B', func)

    expect(result).to.equal('cookie')
    // td.verify(func(), { times: 0 }); // <- this would be redundant and over-prescriptive.
  });
});
```

Since you're stubbing-and-not-verifying this test double function in other cases, that means you're able to assert the subject must do something with that value that you're able to assert in those cases. My default inclination would be to continue to assert the return value of the subject in the case where the stubbing is unnecessary, and simply not care about whether the stub is invoked or not.

There are a few motivations I see most often for wanting to make sure an otherwise stubbed method is _not_ called:

* A desire to specify the interaction. Stubbing specifies this indirectly, but there's nothing in the test preventing an extraneous call to the test double. Well, there's nothing preventing the subject from doing all manner of other extraneous things. You could spend hours making sure the subject doesn't call other third-party functions it has theoretical exposure to, but that would be an unnecessary test (see [Necessary & Sufficient](https://github.com/testdouble/contributing-tests/wiki/Necessary-%26-Sufficient#necessary)). If that's your motivation, I recommend just letting it go unspecified. It's not the responsibility of the test to ensure everything that does not happen.
* A desire to ensure performance is not wasted. If the subject does call `func` extraneously, just delete the unnecessary call and recoup the performance benefit; your tests provide you a safety net that the behavior is correct, which makes such a refactor safe. It's not a responsibility of a unit test to ensure that a test is maximally performant—it's the job of your tests to encode the intended behavior of the subject so that refactoring implementation details can be done with confidence.
* To cover a case where calling the stubbed function under a particular case would, in a production setting, throw an error. If this is the case, then just update the stubbing in the test with `thenThrow()`. If the test continues to pass, then the subject wasn't called. This is preferable to `td.verify` for at least two reasons:
  * It is more consistent with the other stubbings. If you think as a test double as a typed entity (e.g. "a function that has a result" vs. "a function that has a useful side effect"), then treating that type consistently confers a benefit to the reader
  * Setting up a `thenThrow` stubbing conveys intent about the dependency under the given condition—a reader will see it and logically conclude that a _real_ `func` would explode with that input. Simply verifying it wasn't called doesn't really convey any intention other than, I guess, not wanting to waste a call.

So the last case—where calling the function would raise an error—is the only one I'd actually test for, and I'd do it like this:

```js
  it('is does not blow up when B', () => {
    td.when(func()).thenThrow('invalid input!')

    var result subject('B', func)

    expect(result).to.equal('cookie')
  });
```

**Comment by LandonSchropp** [comment]
Thank you for the detailed and thorough explanation! I really appreciate that you took the time to explain this to me. In my case, the reason for verifying was to avoid an expensive call, but as you said, it's probably not the responsibility of the test to ensure that. That also probably ties the tests to a specific implementation, which wouldn't be good if we decide to refactor down the road.

Thanks again, and happy holidays!

**Comment by LandonSchropp** [comment]
I also appreciate the link to the Necessary and Sufficient document. 😃
