### ISSUE TITLE
Possible pollution issue (2 tests work individually, but fails when run together)

### ISSUE THREAD

**Issue by pingvinen** [testdouble/testdouble.js#171]
I have run into a situation where something weird happens. I have tried to reproduce the issue as simply as possible in https://github.com/pingvinen/testdoublejs-issue.

TL;DR: I have 2 tests. When I run them individually they work, but when I run them together, 1 of them fails. I run td.reset() in afterEach and require/replace everything in beforeEach.

The test that fails is trying to verify that another function is being called with a parameter of the correct type. The parameter is an instance of a "class" that is newed inside the method. That class is _not_ replaced in the spec file that fails, but it is td.object()'ed in the other spec file.

The verification fails with the parameter type changing from "SomeClass" to "Object" - but only when running both tests in the same test run.

Have I stumbled upon a bug or am I merely doing something wrong? Any help would be much appreciated.

The output

```
$ npm run test

Failed tests:

  2) moduleA calls someFunction with an instance of SomeClass:

      Unsatisfied verification on test double `.someFunction`.

  Wanted:
    - called with `(anything(), isA(SomeClass))` 1 time.

  But was actually called:
    - called with `({animal: "dog"}, "[object Object]")`.

  
    Wanted:
      - called with `(anything(), isA(SomeClass))` 1 time.
  
    But was actually called:
      - called with `({animal: "dog"}, "[object Object]")`.
      at Object.fail (/home/myuser/workspace/testdoubleissue/node_modules/testdouble/lib/log.js:21:13)
      at Object.module.exports [as verify] (/home/myuser/workspace/testdoubleissue/node_modules/testdouble/lib/verify.js:28:20)
      at lab.test (/home/myuser/workspace/testdoubleissue/test/2_moduleA.spec.js:37:12)
      at Immediate.setImmediate (/home/myuser/workspace/testdoubleissue/node_modules/lab/lib/runner.js:672:36)
      at runCallback (timers.js:637:20)
      at tryOnImmediate (timers.js:610:5)
      at processImmediate [as _immediateCallback] (timers.js:582:5)
```

To clone and trigger the error

```
git clone git@github.com:pingvinen/testdoublejs-issue.git
cd testdoublejs-issue
yarn install
npm run test
```

**Comment by searls** [comment]
Yikes this sounds hideous. Thanks for the example project.

Also you can do `yarn run test` or even better `yarn test` since you're using yarn.

**Comment by searls** [comment]
Another pro-tip, in your package script just do this:

```json
  "scripts": {
    "test": "lab test/"
  },
```

**Comment by searls** [comment]
Is it possible that this is a consequence of the fact lab separates tests via domains as opposed to global state, I wonder?

**Comment by searls** [comment]
Good news, I was able to normalize the example in ES5 and standard then add mocha  to the same test files and verify the issue also occurs in mocha :+1:

**Comment by searls** [comment]
Ok, it took me over an hour to figure out what's going on in here, and it's going to be challenging to explain.

## The workaround/fix

To fix your issue, change this in `test/2_moduleA.spec.js`:

```js
        someFunction = td.replace('../lib/someFunction');
        SomeClass = require('../lib/SomeClass').SomeClass;
```

To this:

```js
        SomeClass = require('../lib/SomeClass').SomeClass;
        someFunction = td.replace('../lib/someFunction');
```

## Explanation

In short, what's happening here is that [quibble](https://github.com/testdouble/quibble), as soon as it encounters a `td.replace` call that will require module-replacement it will patch Node's `Module._load` so that no subsequent `require` calls that originate from the same file will hit the `require` cache.

The reason it bypasses the cache is because, typically any subsequent `require` calls will be of the subject under test, and if it has been loaded previously we want to ensure that it's a cache miss (so that, should it `require` any modules that have been swapped out via `td.replace`, it will be fully re-evaluated). 

Because any module that's re-evaluated will be redefining any functions, each time `SomeClass` is `require`'d after the first `td.replace` module, each `SomeClass` variable will refer to a different `SomeClass` definition, and as a result any instances will fail an `instanceof` check. That is what you were encountering by using the `td.matchers.isA` matcher (which relies on `instanceof`).

To workaround this, require any non-replaced-dependencies that are not the subject under test prior to to doing `td.replace` calls. I think this is actually a pretty natural thing to expect users to do, since in general `require` statements normally sit at the very top of a listing unless there's a reason they need to be done dynamically (as they do when we're replacing modules inside a test).

In summary, my recommendation would be to write tests like this:

```js
const Lab = require('lab');
const lab = exports.lab = Lab.script();
const td = require('testdouble');
const SomeClass = require('../lib/SomeClass').SomeClass;

lab.experiment('moduleA', () => {
    console.log('A');

    let someFunction;
    let moduleA;

    lab.beforeEach((done) => {
        someFunction = td.replace('../lib/someFunction');

        moduleA = require('../lib/moduleA');

        done();
    });
```

There's nothing that can be done to prevent this behavior, as it's the only hook quibble has available to itself. I regard it as an extreme edge case for the reasons above. As a result this probably shouldn't crop up in practice very often and is at least avoidable by the end-user. Not sure what else can be done, so I'm going to close this out.

For what it's worth, I also went to the trouble of downgrading to ES5, adding mocha (to ensure the problem wasn't lab-related), and applying standard. I also moved the `require` statements as high up the listing as I could given the module replacement issue described here. You can check out that repo here: https://github.com/searls/testdouble-issue-171

**Comment by pingvinen** [comment]
Thank you @searls for your very thorough analysis - it did the trick.
