### ISSUE TITLE
Replacing methods on `window.location`

### ISSUE THREAD

**Issue by alexlafroscia** [testdouble/testdouble.js#183]
I've been unable to replace methods on `window.location`, (or the entire `location` object, for that matter).  Is this because the browser prevents these modifications?  Is there some way that's suggested for this?  For example, I wanted to replace the `window.location.replace` method to verify that a redirect would happen, without the page actually changing.

I've created a repo with a reproducible example case here:

https://github.com/alexlafroscia/testdouble-replace-location

**Comment by searls** [comment]
Replacing host variables generally isn't encouraged, but besides, `window.location` is read-only, which is why that won't work: https://developer.mozilla.org/en-US/docs/Web/API/Window/location

We recommend wrapping third-party APIs in methods that you own, and then replacing those instead. That way if it's hard to work with or to fake, you're in control and can alleviate that pain by changing the API.
