### ISSUE TITLE
sinon.sandbox analog?

### ISSUE THREAD

**Issue by wizardzloy** [testdouble/testdouble.js#188]
Some test runners, e.g. `ava`, can execute your tests in parallel. Having a single "mocking" context might lead to race conditions when doing `td.reset()`. Is there a way of creating an isolated mocking context that could be restored independently of the other tests, like `sinon.sandbox` provides?

**Comment by searls** [comment]
There is not, but if you consider what `sinon.sandbox` does and what `td.reset` applies to, I'm not sure there's much daylight for an additional feature to exist.

Sandbox is a really odd feature, that I think is more intended to (1) scope global sinon configuration down, and (2) give some way of resetting more than one double at a time (I don't believe there is a global `sinon.reset`, which was the major reason I'd see anyone using the sandbox feature at all.

In fact, take a look here for why sandbox doesn't actually solve the problem you suggest it would: https://github.com/avajs/ava/issues/1066 -- as long as you're globally replacing something, you can't run tests concurrently safely, full stop.

---

So instead what I'd suggest is to either (1) mark your unit tests that use td.js to replace production-side code as `.serial`, or (2) avoid using `td.replace` at all for async tests and instead use traditional/manual dependency injection to get your fakes to your subject.

Fears of running `serial` as undercutting the value of ava are, I believe, unfounded if you're using td.js to write isolated unit tests. Since that means they're not doing any I/O, running them concurrently intra-process doesn't buy you much. Each _file_ is still tested concurrently by ava in a separate process, but intra-file specs would be run serially for your isolated unit tests. And that advice applies to both Sinon & td.js

**Comment by searls** [comment]
I wrote more about this last year here: https://github.com/testdouble/testdouble.js/issues/131#issuecomment-254540398
