### ISSUE TITLE
How do I stub a function that being promisify'd by bluebird?

### ISSUE THREAD

**Issue by stringbeans** [testdouble/testdouble.js#200]
Hi!

I have a function that does something like this...

```
function someFunction(sqs, message) {
  const sendMessage = Promise.promisify(sqs.sendMessage.bind(sqs));
  return sendMessage(message)
}
```

How would I setup a test such that i can verify whether `sendMessage` is called correctly? I understand I can just pass the "promisified" version of sendMessage into `someFunction` and that eases the stubbing, but it makes my code a little messy. 

As for the signature of `sqs.sendMessage` it would be `(message, callbackFn)`

Thanks in advance!

**Comment by searls** [comment]
Since the promisification is an implementation detail of the function, then the public contract between it and the test is that `sqs` should be passed something that expects the callback. As a result, I would pass it a test double wired to respond to a callback and verify that it returns a promise that resolves to the expected value:

```js
// assuming you have a done() callback or something
var sqs = td.object(['sendMessage'])
td.when(sqs.sendMessage('lol')).thenCallback(null, 'kek')

var result = someFunction(sqs, 'lol')

result.then(function(result) { 
  assert.equal(result, 'kek')
  done()
})
```

**Comment by stringbeans** [comment]
@searls thank you very much!
