### ISSUE TITLE
When stringifying args, use a testdouble's name if it has one

### ISSUE THREAD

**Issue by BaseCase** [testdouble/testdouble.js#21]
If I want to `verify` that a testdouble object is called with an argument of another testdouble, it might be nice to show the name of the argument testdouble in the error message. An example:

Given:
```javascript
var foo = td.create('named_foo');
var bar = td.create('named_bar');
td.verify(bar(foo));
```
the error message will be:
```
Error: Unsatisfied verification on test double `named_bar`.

  Wanted:
    - called with `(undefined)`.

  But there were no invocations of the test double.
```
It could be useful if the error message instead had the line:
```
    - called with `(named_foo)`.
```

This is related to [a twitter conversation](https://twitter.com/searls/status/642053536470188033) where `toString()` is also mentioned; I'm not 100% sure how that plays into it but that will probably become clear when I check out the source a bit more.

**Comment by searls** [comment]
Don't worry about the toString() stuff, I was being overly paranoid. Since a testDouble itself is just a function, I'd add a toString() prop to it to implement this (in the event that a name is set).

```
> foo = function(){}
> foo.toString = function() { return 'such a foo'; }
> s = "hi" + foo + "bye"
```

So my vote is that wherever we're setting the name now, also add a quick `testDouble.toString ||= -> name`
