### ISSUE TITLE
Verifying a td.constructor() fails

### ISSUE THREAD

**Issue by em77** [testdouble/testdouble.js#278]
Verifying a` td.contructor()` fails with `No test double invocation detected for 'verify()'`. Using the code example from #248 and passing an array of methods fails.

Example: https://runkit.com/em77/5980a049e5b45000133889da

Is this intended behavior? If so, how should I verify a constructor for which I don't have a class?

**Comment by searls** [comment]
Great catch, this is absolutely a bug and it went uncaught, because `td.constructor()` is only tested when it's passed a function to fake (as that's how I almost always use it myself)

This runkit, for example, where it's given a function and then imitates that function works fine: https://runkit.com/searls/5980b4e0a0f33a001257e9c0

**Comment by rachel-carvalho** [comment]
For now we created a fake class inline with the methods we need to stub and we're passing it to `td.constructor(FakeClass)` as a workaround.

**Comment by searls** [comment]
yeah, that should work for the moment

**Comment by searls** [comment]
Fixed by ebe5796fd19a5fe668d7bf0eeb1cc5e7175f6945

**Comment by searls** [comment]
Landed in testdouble@3.2.3

**Comment by gordody** [comment]
It would be nice to add this into the docs as well...

Use case 1:
`var MyStubbedClass = td.constructor(MyClass);`
`// code that creates MyClass -> MyStubbedClass`
`td.verify(MyStubbedClass(initParams));`

Use case 2:
`var MyStubbedClass = td.replace('path/to/my_class.js')`
`// code that creates MyClass -> MyStubbedClass`
`td.verify(MyStubbedClass(initParams));`
