### ISSUE TITLE
verifiable thenThrow

### ISSUE THREAD

**Issue by andreventuravale** [testdouble/testdouble.js#288]
Hi,

I would like to have a way to accomplish a verifiable thenThrow.

Ex:
```javascript

    describe('Question 1', function () {

        describe('Given a closure as argument that causes an error when executed', function () {

            beforeEach(function () {

                this.closure = td.function();

                td.when(this.closure()).thenThrow('foo');
            });

            it('Find a way to handle this error', function () {

                expect(function () {

                    answers.question1(this.closure);

                }.bind(this)).not.throws();

                td.verify(this.closure());
            });
        });
    });

```

This code always fail, if I put the td.verify within a try-catch it pass but as a false positive.

I think I might be able to verify a call without side effects, but I have no sure if it is a bug or something that I could not understand or do correctly.

**Comment by andreventuravale** [comment]
Found a way to do it:

```javascript
expect(td.explain(this.closure).callCount).to.be.greaterThan(0);
```
Not sure if it is correct though.
Thanks.

**Comment by searls** [comment]
Two notes:

1.) It's not necessary to verify calls that you have also stubbed, so this shouldn't be a real issue. If the verification feels necessary then the stub must not be necessary.

2.) Because the stubbing throws an error, a `td.verify` demonstration will also throw an error. Your only option if you really want to do this is as you stated.
