### ISSUE TITLE
Can I use test double with enzyme on client end to test if method runs on button click ?

### ISSUE THREAD

**Issue by Sandeep3005** [testdouble/testdouble.js#297]
New to TDD.
Making an app with Meteor and React using mocha and expect for client end.
Can I use test double with enzyme to test the functionality of button click? and other features.

Example
**Header.jsx**

```
export const PrivateHeader = (props) => {
  logout = () => {
    Accounts.logout();
  }
  return (
    <div className="header">
      <div className="header__content">
        <h1 className="header__title">{props.title}</h1>
        <button className="button button--link-text" onClick={this.logout}>Logout</button>
      </div>
    </div>
  );
};

PrivateHeader.propTypes = {
  title: React.PropTypes.string.isRequired
};

```

** Header.test.js**
```
import { Meteor } from 'meteor/meteor';
import React from 'react';
import { mount } from 'enzyme';
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-15.4';

import Header from './Header';

configure({ adapter: new Adapter() });

if (Meteor.isClient) {
  describe('Header Test', function () {
    it('should logout user on button click', function() {
      const titleProp = 'Test Title';
      const wrapper = mount(<PrivateHeader title={titleProp} />);
      wrapper.find('button').simulate('click');
      /*    How to proceed from now     */
    });
  });
}
```

Please if someone could guide me in the right direction.
Or if not test double which library will be most suitable, I don't wanna make any change in souce code for testing.

**Comment by searls** [comment]
It may be possible, but for something that integrated, I don't think I'd recommend using a test double library. I'd create an artificial UI event instead, as opposed to trying to use testdouble.js to poke a hole in any particular method. td.js is designed to fake out APIs you own, so that it can influence their design by responding to pain—I suspect in this case you'd be faking methods you don't own, which would result in useless pain.

**Comment by searls** [comment]
(Note, I am not an expert in testing React components and may be off base)
