### ISSUE TITLE
Using invocation verification with QUnit

### ISSUE THREAD

**Issue by skaterdav85** [testdouble/testdouble.js#304]
Hey Justin, thanks for the library! Love it!

I'm currently using testdouble with QUnit via Ember. QUnit expects each test to have at least one assertion, but it doesn't recognize `td.verify()` as an assertion. A few work around are:

1. Put `assert.expect(0)` at the top of the test. I don't like this because `td.verify()` is an assertion and this is saying there are no assertions.
2. Put `assert.ok(true)` after `td.verify()`.

I considered doing something like `assert.ok(td.verify(...))`, but `td.verify()` returns `undefined`. This approach seems the most clear if `td.verify()` returned something truthy. Have you heard of anyone experiencing this issue and how they solved it? If not, what are your thoughts on having `td.verify()` return `true` when the assertion passes?

**Comment by searls** [comment]
I would recommend creating a test helper that wraps `td.verify` to do what you want and does something like this in a suite-wide test helper file:

```js
global.td = require('testdouble')
const originalVerify = td.verify
td.verify = function(...args) {
  originalVerify.apply(this, args)
  assert.ok(true)
}
```

If you can get that to work, you should consider publishing a qunit plugin similar to `testdouble-jasmine` and `testdouble-chai` to help others!

**Comment by skaterdav85** [comment]
thanks Justin!

**Comment by alexlafroscia** [comment]
I added a QUnit assertion that internally calls `td.verify` for this purpose.

In a "test setup" file, I added the following:

```javascript
import QUnit from 'qunit';
import td from 'testdouble';

QUnit.extend(QUnit.assert, {
  verify() {
    try {
      td.verify(...arguments);

      this.pushResult({
        result: true,
        message: 'Stub passed verification'
      });
    } catch ({ message }) {
      this.pushResult({
        result: false,
        message
      });
    }
  }
});
```

This allows me to use `assert.verify` in my tests with the same ergonomics as `td.verify`, but it automatically shows the rich TestDouble verification error message in the QUnit UI if the verification failed.

**Comment by searls** [comment]
Might it make sense to extract this into a testdouble-qunit module? Similar to testdouble-chai or testdouble-jasmine?

**Comment by alexlafroscia** [comment]
I was thinking the same. I can give that a shot in the next few days

**Comment by alexlafroscia** [comment]
Done! 

http://alexlafroscia.com/testdouble-qunit

**Comment by searls** [comment]
Hey @alexlafroscia, a few points of feedback you might be able to work into that package ([github](https://github.com/alexlafroscia/testdouble-qunit))

1. Any chance you can eliminate the [3 hard deps](https://github.com/alexlafroscia/testdouble-qunit/blob/master/package.json#L24-L26) on ember/broccoli stuff? That's going to blow up the install size/time for non-ember-cli users 

2. Currently [you're importing `testdouble`](https://github.com/alexlafroscia/testdouble-qunit/blob/master/lib/testdouble-qunit.js#L2), but AFAICT you aren't actually depending on it anywhere (though your devDep on the ember-cli-testdouble extension is probably bringing this along for you). Instead, I would recommend you expose a public interface that received the user's testdouble object as an argument to initialize itself, so that you can both have certain access to a `td` instance without marrying the plugin to any particular version range of testdouble. This is how [testdouble-jest](https://github.com/testdouble/testdouble-jest), [testdouble-chai](https://github.com/BaseCase/testdouble-chai), and [testdouble-jasmine](https://github.com/BrianGenisio/testdouble-jasmine#global)

It'd be super fantastic if testdouble-qunit could accomplish both of these things

**Comment by alexlafroscia** [comment]
Sure, I can split it out into a more generic package and an Ember addon. I modeled the approach after `qunit-dom` which does essentially the same thing, shipping as an Ember addon by default (since QUnit is primarily used with Ember apps) but contains a library that could be used independently as well

**Comment by alexlafroscia** [comment]
Just to follow up, it's now two separate repos:

- `testdouble-qunit` doesn't have a direct dependency on with `QUnit` or `test-double` and instead expects to have them passed in as arguments
- `ember-cli-testdouble-qunit` wraps it and packages it for consumption by an Ember app

There's a whole documentation site here:

https://alexlafroscia.com/testdouble-qunit

**Comment by searls** [comment]
Fantastic! Thanks for aping the style of the other plugins!

**Comment by searls** [comment]
Threw it in the README https://github.com/testdouble/testdouble.js/commit/8ba9ba00e815383bcea618145cbe885504e796cf

**Comment by alexlafroscia** [comment]
Sure thing! I did notice that I unintentionally swapped the argument order that the others use in some cases. Do you have a preference on consistency with other tools? I'm happy to change it if you'd rather.
