### ISSUE TITLE
slow performance when replacing big modules

### ISSUE THREAD

**Issue by slavab89** [testdouble/testdouble.js#340]
When using `td.replace` on big modules such as `request-promise` it take a lot of time (almost 1 second!)
I've created a runkit to demostrate this. When i'm running it on my browser it takes around 500ms (which is still a lot for a test i believe)
https://runkit.com/slavab89/5a845a337bdbe50012dea485

When i have a lot of tests that do that logic in BeforeEach, it makes it very slow.

Maybe there should be a possibility to reset only the call counters of all the "when"s somehow?

**Comment by searls** [comment]
We [recommend against](https://github.com/testdouble/contributing-tests/wiki/Don%27t-mock-what-you-don%27t-own) using `td.replace()` to replace 3rd-party dependencies at all, and [warn that this is slow](https://github.com/testdouble/testdouble.js#specifying-a-custom-replacement). 

Personally, I'd recommend isolating most 3rd party dependencies to the periphery of the app by making custom wrappers (i.e. `wrap/request-promise.js`) that only exports the minimum functions your app uses, potentially translating them to cleaner function signatures that mirror how you design the rest of your code.

I don't think a productive workaround to this would be absorbing some amount of state pollution across test cases to avoid the cost of imitating the dependency (since tracking changes at every single level of a complex replacement would probably cost as much as just re-imitating it, but it'd be an interesting perf optimization experiment)
