### ISSUE TITLE
How to mock typescript abstract class?

### ISSUE THREAD

**Issue by stepan-prokipchyn** [testdouble/testdouble.js#356]
### Description
I'm trying to mock abstract class without implementation:
```js
it("should call dismiss when close is clicked", () => 
    {
        var notificationService = td.object(INotificationService.prototype);

        var component = new NotificationComponent(notificationService);
        component.reportCloseClicked();

        td.verify(notificationService.dismissRequested());
    });
});
```
### Issue

'dismissRequested' is not found in 'notificationService'

**Comment by stepan-prokipchyn** [comment]
```js
import { Observable } from 'rxjs/Observable';

/**
 * @interface INotificationService
 * 
 * @brief Interface for classes which handles notification behaviour.
 * 
 * This interface hides specific notification behaviour behind standard actions.
 */
export abstract class INotificationService {

    /**
     * @brief Called when user presses dismiss button.
     * 
     * Notification component might be hidden by implementation.
     */
    abstract dismissRequested();

    /**
     * @brief Called when user presses "More information" button.
     * 
     * Usually new page or popup will be shown.
     */
    abstract detailsRequested();
};
```

**Comment by searls** [comment]
This is just a guess, but you probably want your test to use `td.constructor`, not `td.object`.

```
var NotificationService = td.constructor(INotificationService);
```

The fake `NotificationService` that results can then be instantiated by your test or your subject

**Comment by stepan-prokipchyn** [comment]
@searls thank you for suggestion. However I'm getting the following error in your code:
`Argument of type 'typeof INotificationService' is not assignable to parameter of type 'Constructor<INotificationService>'.`
Do you think a test project which reproduces the issue might help?

**Comment by searls** [comment]
Sure, but I have to admit I'm hardly a typescript expert.

**Comment by stepan-prokipchyn** [comment]
@searls , I ended up with the following approach that works for me:
`var notificationService = <INotificationService>td.object(["dismissRequested"]);`
So, I have to mock some anonymous object with all methods I need and then cast it to my base class. From one side this is more verbose, but from other side - it's more clear which methods are used.

What do you think about that?

I've also created a question about how to get a list of abstract methods to mock them automatically:
https://stackoverflow.com/questions/49487176/is-it-possible-to-iterate-typescript-class-abstract-methods-in-run-time

**Comment by searls** [comment]
Sorry, I'm not familiar enough with TypeScript to comment. Paging @duluca in case he has time

**Comment by duluca** [comment]
@stepan-prokipchyn @searls given `export function constructor<T>(constructor: Constructor<T>)` and the type error you posted, it is expected that INotificationService should be implementing the interface `Constructor<T>`. The interface `Constructor<T>` requires the implementer to have a constructor defined. In this case, we are talking about an abstract class, which is not meant to be instantiated, so we're trying to fit a square peg in to a round hole.

Taking a step back, and given the sample code you've provided, INotificationService shouldn't be an abstract class at all, but an actual interface, since your abstract class doesn't contain any implementation. `interface INotificationService`. A quick tip, the `I` in `INotificationService` by convention stands for _interface_, an abstract class should be named more like `BaseNotificationService`.

In either case, mocking or unit testing an abstract class of abstract functions or an interface isn't very useful, since they merely define the contract of an implementation and not an actual implementation. Here's a good discussion: https://softwareengineering.stackexchange.com/a/301080. 

I would personally stay away from layers and layers of abstraction that ultimately requires convoluted solutions to simple problems.

**Comment by searls** [comment]
Speaking from distant memory, @duluca, for the first 5-8 years of the existence of mocking libraries (over in Java-land), mocking an interface was seen as the _only_ appropriate thing to mock, because coupling a test+subject to the _contract_ of a dependency was seen as looser than to coupling it to any one implementation. (This coincided with interface-heavy libraries like Spring, and was also complicated by the fact that mocking classes was more tricky technically.)

I think it's a valid thing to want to do, but I am also easily convinced our current typescript support is too limited to enable this. (As an aside, my limited experience playing with Typescript has led me to some disappointment that type declarations are erased upon compilation and can't be introspected at runtime—would make our lives a lot easier)

**Comment by duluca** [comment]
@searls You're absolutely right. I mistakenly converged two different concerns in my mind of what is **Under test** vs what is being **mocked**, and wrote my response solely considering that the `abstract` class is what is **Under test.**  

In between the touch points of APIs, services, classes, etc., we want to be using an `interface` to _pretend_ that we're injecting a concrete implementation to a what is **Under test**. In JavaScript we don't have to worry about injection, because of the dynamic typing, so we end up passing a concrete implementation in, TypeScript verifies the implementation adheres to the `interface` at build time and we have reasonable certainty that things will work fine at run-time.

@stepan-prokipchyn In terms of the practicalities of mocking in JavaScript using `td` and the way the TypeScript typings are defined, it'd then only make sense to pass in a concrete implementation of an `interface` in to `td.constructor`. 

@searls A TypeScript implementation of `td.constructor` would make the `Constructor<T>` interface superfluous. We can make sure that the developer is providing the correct concrete implementation by type checking at build time, like below:

```
interface IMyInterface {
  a: string
}

class MyConcreteImpl implements IMyInterface {
  public a: string
}

function construct<TInterface>(concrete: TInterface & Object): TInterface {
  let mockedObject: TInterface
  //... td magic
  return mockedObject
}

//sample use
construct<IMyInterface>(new MyConcreteImpl())
```

Here's the TS playground link: https://www.typescriptlang.org/play/index.html#src=interface%20IMyInterface%20%7B%0D%0A%20%20a%3A%20string%0D%0A%7D%0D%0A%0D%0Aclass%20MyConcreteImpl%20implements%20IMyInterface%20%7B%0D%0A%20%20public%20a%3A%20string%0D%0A%7D%0D%0A%0D%0A%0D%0Aconstruct%3CIMyInterface%3E(new%20MyConcreteImpl())%0D%0A%0D%0Afunction%20construct%3CTInterface%3E(concrete%3A%20TInterface%20%26%20Object)%3A%20TInterface%20%7B%0D%0A%20%20let%20mockedObject%3A%20TInterface%0D%0A%20%20%2F%2F...%20td%20magic%0D%0A%20%20return%20mockedObject%0D%0A%7D

My colleague @kgroat has some ideas about making this better.

**Comment by kgroat** [comment]
I've gotten a rudimentary implementation down for how this could work in TS; check out the [TS Playground](http://www.typescriptlang.org/play/#src=interface%20IMyInterface%20%7B%0D%0A%20%20%20%20myProp%3A%20string%0D%0A%7D%0D%0A%0D%0Aclass%20MyConcreteImpl%20implements%20IMyInterface%20%7B%0D%0A%20%20%20%20myProp%3A%20string%20%3D%20'default'%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aimitate%3CIMyInterface%3E(MyConcreteImpl)%0D%0A%0D%0Atype%20Constructor%3CT%3E%20%3D%20%7B%20new%20()%3A%20T%20%26%20Object%20%7D%0D%0A%0D%0Afunction%20imitate%3CTInterface%3E(concrete%3A%20Constructor%3CTInterface%3E)%3A%20TInterface%20%7B%0D%0A%20%20%20%20const%20val%20%3D%20new%20concrete()%0D%0A%20%20%20%20const%20target%20%3D%20%7B%7D%20as%20TInterface%0D%0A%0D%0A%20%20%20%20%2F%2F%20You%20can%20still%20iterate%20over%20all%20the%20properties%20and%20functions%0D%0A%20%20%20%20const%20props%20%3D%20gatherProps(target)%0D%0A%20%20%20%20Object.defineProperties(target%2C%20props)%0D%0A%0D%0A%20%20%20%20return%20target%0D%0A%7D%0D%0A%0D%0Afunction%20gatherProps%3CT%2C%20TOut%20%3D%20%7B%20%5BP%20in%20keyof%20T%5D%3A%20PropertyDescriptor%20%7D%3E(thing%3A%20T)%3A%20TOut%20%7B%0D%0A%20%20%20%20const%20props%20%3D%20%7B%7D%20as%20TOut%0D%0A%20%20%20%20Object.getOwnPropertyNames(thing).forEach((propName)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20if%20(!props%5BpropName%5D%20%26%26%20propName%20!%3D%3D%20'constructor')%20%7B%0D%0A%20%20%20%20%20%20%20%20props%5BpropName%5D%20%3D%20Object.getOwnPropertyDescriptor(thing%2C%20propName)%0D%0A%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D)%0D%0A%20%20%20%20return%20props%0D%0A%7D) I was using to make sure the concepts worked.  I used the `imitate` function as a guideline, because it seems that is the function which is doing the work under the hood for `constructor`.

The idea is that you define a `Constructor` type defined as such:
```typescript
type Constructor<T> = { new (): T & Object }
```
This allows you to ensure that the thing passed into the `imitate` function is, indeed a `class`.

**Comment by searls** [comment]
@kgroat sounds reasonable.

Am I being naive in wishing for a way to imitate an interface that lacks any existing concrete implementation? If you're practicing TDD from the outside-in and creating invoices as you go, it'll often be the case that you're writing the test of a subject that calls a dependency on some interface (say, `Persistable`) and it may be a clearer test, less work, and less coupling to just say "hey `td`, give me a `Persistable` fake" than to go to the trouble of designing a fake one. This is especially true in cases where the interface being faked is very simple but all the concrete things implementing it are overly complex and large.

If you followed that far, I think what I want is:

```ts
let persistable = td.typeOf<Persistable>()
let subject = cacheThingy(persistable)

subject(42)

td.verify(persistable.save(42))
```

I'm dubious there's a way to make this work but rather than assume things or spend all day hunting for it, I'd love your thoughts on whether it's feasible

**Comment by stepan-prokipchyn** [comment]
@searls, @kgroat, @duluca, thank you for your help. Let me clarify my task a little bit. 
Yes, as @searls supposed, I'm trying to mock an interface which does not have an implementation (and probably will not have in the near future). That is why I chosen Typescript over Javascript - I want to have OOP support. 
I was using abstract class instead of interface because there is no difference in terms of OOP. At the same time, I was hoping to get more RTTI information from abstract class. Typescript interface is compiled into nothing while abstract class is compiler to normal Javascript object.

My current solution works fine for me:
`var notificationService = <INotificationService>td.object(["dismissRequested"]);`

Looks like there is no better way, because abstract classes do not have abstract methods list in runtime. I think if you guys do not have anything to add, we could close this issue.

**Comment by searls** [comment]
Well, if the abstract class that you get at runtime has enough metadata to know what methods are supposed to be on concrete subclasses, then I could imagine a new code branch in `td.constructor(MyAbstractClass)` which would detect that it's looking at TS abstract class metadata (which I imagine is reasonably detectable) and then create a fake sub-type of.

This is speculative enough that I might suggest you try spiking it out in its own module first, but I think it's a worthwhile idea.

**Comment by stepan-prokipchyn** [comment]
@searls, I have not found a way of achieving this. INotificationService.prototype does not contain abstract methods as well as getOwnPropertyNames.

**Comment by searls** [comment]
What does it provide?

**Comment by lgandecki** [comment]
Hey guys. This is possible now, please take a look at https://github.com/testdouble/testdouble.js/blob/master/docs/10-using-with-typescript.md
