### ISSUE TITLE
Multiple stubs, count wrong?

### ISSUE THREAD

**Issue by gonzalonaveira** [testdouble/testdouble.js#387]
### Description
I'm doing multiple stubs on an object, the stubs seems to work but when I check the call count it's zero.
In the example I provide i want to verify on the `log` function that it was called with the proper parameters.

After debugging it I verified that the parameters are correct, I also tried with `td.matchers.anything()`.

### Environment

-Node 8.11.1
-npm 6.4.1
-testdouble 3.8.2

### Example Repo

https://github.com/gonzalon/node-ut

**Comment by searls** [comment]
Your issue is that your test executes synchronously and exits immediately, but your subject is asynchronous and doesn't exit until at least two additional ticks of the event loop.

Annotated source:
```js
    // You're good so far
    math.sum(a, b).then( (r) => {
        // All of this will execute in the next tick (after the test has exited)

        math.log(r);

        // Therefore, at test-time, this call won't have happened yet:
        math.substract(a, b).then( (rs) => {
            // And this is now scheduled at least one tick later
            math.log(rs);

            const body = {sum: r, substract: rs};

            // To test this, you need some kind of mechanism (a callback,
            // a returned promise, etc.) to continue execution of the test
            res.status(200).send(body);
        })
    });
```

Options:

1. Refactor the subject to not be fire-and-forget, which would be good form as that's as unobservable as a private anonymous function. For how to write async tests in Jest I'll have to refer you to [their docs](https://jestjs.io/docs/en/tutorial-async)

2. Configure a fake promise implementation which will execute synchronously for you. I wouldn't recommend this as you might find other bugs sneak in due to synchronous execution of code that will always be async in prod. [docs](https://github.com/testdouble/testdouble.js/blob/master/docs/5-stubbing-results.md#using-non-native-promise-libraries)
