### ISSUE TITLE
Unsure how to replace module that returns just a closure.

### ISSUE THREAD

**Issue by laduke** [testdouble/testdouble.js#431]
### Description
I was trying to wrap a dependency that has an API like this, but I do it too. 

```js 
// greeter.js
module.exports = function Greeter (greeting) {
  return function (name) {
    return `${greeting}, ${name}`
  }
}
```

I'm not sure how to set up a test of something that depends on Greeter. I searched through the issues and docs; Sorry if I'm skipping over something that's already talked about! 

```js
// test
module.exports = function () {
  const Greeter = td.replace('../lib/greeter.js')

  /*
    td.when(???).thenReturn('hi, bob')
  */

 // requires Greeter
  const MyThing = require('../lib/my-thing')

  const subject = new MyThing()
  const result = subject.uppercaser()

  assert(result, 'HI, BOB')
}
```

This example is pretty nonsensical.  

Here's an example module that has a similar API
https://github.com/mikeal/bent

You set it up with some context like:
`const post = bent('http://localhost:3000/', 'POST', 'json', 200);`

and it returns you the function to call later
`const response = await post('cars/new', {name: 'bmw', wheels: 4});`

I worked around it by wrapping in a class with just one method, which testdouble makes super easy and I appreciate!

**Comment by searls** [comment]
The unsatisfying-but-intentional answer to most questions of hard-to-mock things is "the fact this is hard to mock is evidence that this API is hard-to-use, so don't design your API that way". This usually leads to a reply of "well I don't control the API, it's a 3rd party library". Which then would prompt me to reply [don't mock what you don't own](https://github.com/testdouble/contributing-tests/wiki/Don%27t-mock-what-you-don%27t-own)

Failing convincing anyone not to use the library a certain way, this isn't actually _that_ hard to mock of an API and you can certainly tactically do what you're suggesting:

```js
const td = require('testdouble')

function Greeter (greeting) {
  return function (name) {
    return `${greeting}, ${name}`
  }
}

const fakeGreeter = td.imitate(Greeter)

td.when(fakeGreeter('Ahoy')).thenReturn(name => `wassup, ${name}`)

console.log(fakeGreeter('Ahoy')('pants'))
// prints 'wassup, pants'
```

**Comment by laduke** [comment]
Thanks! That's not bad. Sorry, hadn't got familiar imitate yet. 
(I wasn't gonna try to mock what I don't own, mostly thanks to your writings)


I defer to your experience and wisdom on the hard-to-mock -> hard-to-use in-most-cases stance.

I feel like these do the same thing, but personally prefer one of them...

```
function Closurey (a) {
  return function (b) {
    return `${a}${b}`
  }
}

class Classy {
  constructor (a) {
    this.a = a
  }

  run (b) {
    return `${this.a}${b}`
  }
}
```
Anyways!
