### ISSUE TITLE
Double Replacement Makes It Impossible to Reset to Original Function

### ISSUE THREAD

**Issue by theodorewahle** [testdouble/testdouble.js#432]
### Description

I often try to use td.replace() on the same function twice, and then when I call td.reset(), there is no way to make that function that I replaced  point to the original function.

### Issue

```js
const td = require('testdouble');
const module = require('../../module');

suite('Name of Test Suite', function() {
  setup(function() {
    // 1st replacement
    td.replace(module, 'fn');
  });

  teardown(function() {
    return td.reset();
  });

  test('1st test', function() {
    module.fn();
  });

  test('2nd test', function() {
    // 2nd replacement
    td.replace(module, 'fn');
    module.fn();
  });
});
```

If you look at the snippet above, there is two calls to td.replace(). After the second replacement, there is no way to get back to the original function. Any number of calls to td.reset() will result in my `fn` still be a td.

 ### My solution
I would like to implement a modification to `td.replace()` such that it maintains a _stack_ of replaced functions. And if you call td.replace() it clears the stack and points the function back to what was originally replaced. That way, you can `td.replace()` on something that is already a testdouble.

What do y'all think?

**Comment by searls** [comment]
This behavior isn't something we set out to support --replacing a dependency multiple times with different things during a test run is likely to lead to confusion, hard-to-debug issues (because activity against a prior-but-deleted test double may no longer be reachable), and diminished test isolation (where the subject might get two different things when requiring the same module twice, which can't happen in real-life production code because of how Node's module cache works).

Along the same lines, this is also why `td.reset()` is a single nuclear option. It needs to get people back to a clean state between tests where they could just as easily call through to a real dependency as replace it again. If calling `td.replace()` multiple times erroneously led to a `td.reset()` call not actually resetting the environment, the only place it would rear its head is on a subsequent test when/if the pollution this caused broke something. As a result, I'm :-1: on this suggestion, and would propose you work around it by either reorganizing your code to only replace a single module once per reset.

**Comment by theodorewahle** [comment]
> This behavior isn't something we set out to support --replacing a dependency multiple times with different things during a test run is likely to lead to confusion, hard-to-debug issues (because activity against a prior-but-deleted test double may no longer be reachable), and diminished test isolation (where the subject might get two different things when requiring the same module twice, which can't happen in real-life production code because of how Node's module cache works).
> 
> Along the same lines, this is also why `td.reset()` is a single nuclear option. It needs to get people back to a clean state between tests where they could just as easily call through to a real dependency as replace it again. If calling `td.replace()` multiple times erroneously led to a `td.reset()` call not actually resetting the environment, the only place it would rear its head is on a subsequent test when/if the pollution this caused broke something. As a result, I'm 👎 on this suggestion, and would propose you work around it by either reorganizing your code to only replace a single module once per reset.

Totally understand. Thanks for the response!!

**Comment by theodorewahle** [comment]
@searls what if I added made it so that it throws an error or warning if someone calls td.replace() on something that is already a testdouble? Would that be useful?

**Comment by searls** [comment]
At first glance that seems reasonable; I can't think of a case where it'd be appropriate to call replace on a test double
