### ISSUE TITLE
Questions: are es6 modules supported?

### ISSUE THREAD

**Issue by goldbergyoni** [testdouble/testdouble.js#434]
First, thanks for the great work here.

Just a question - are es6 modules supported (given that its cache is not exposed via hooks yet)?

I need this info to update my testing guide here:
https://github.com/goldbergyoni/javascript-testing-best-practices

**Comment by searls** [comment]
If you're talking about Node's native ESM support specifically, I can't imagine it'd work natively (it's been a year since I've looked) for the same reason. In general, any support has been indirect thanks to people achieving ESM via transpilers (which were just calling require under the hood)

**Comment by searls** [comment]
That said, it's only the test that needs to drop down to using `require()` calls. The production code should be able to be 100% ESM without any changes to support the test

**Comment by NullVoxPopuli** [comment]
ESM is shipped natively everywhere now. Can testdouble ship `module`? and especially, _browser_ modules? (no require, no `global` global, etc)

**Comment by searls** [comment]
@NullVoxPopuli seems reasonable? I have to own my ignorance here because I've never published a native module-module. I'd be open to someone showing how or opening a PR that adds it, though, for sure! Also, obligatory @giltayar mention since he actually knows ESM well

**Comment by giltayar** [comment]
@NullVoxPopuli I'm not sure what you mean by "`module`" or by "browser modules".

**Comment by electerious** [comment]
Here's an ESM setup I'm currently trying to use, but the replaced module is only replaced inside the test, not in the function calling it. This leads me to the same question: Are ES Modules supported and isn't the `replaceEsm` function pretending that they are?

- My package contains `"type": "module"` inside the `package.json`
- All files are ESM files and are using import/export
- I'm testing with AVA and I'm running it with `testdouble` as a  loader (`--loader=testdouble`)

The module I'm trying to test:

```js
import something from './something.js'

export default {
  get: () => something.fromApi()
}
```

The `something` file:

```js
export default {
  fromApi: () => 0
}
```

The test:

```js
import test from 'ava'
import moduleToTest from '../src/moduleToTest.js'
import * as td from 'testdouble'

test('returns 1', async (t) => {
  const something = (await td.replaceEsm('../src/something.js')).default
  console.log(something) // Just to check that it exists and yes it does
  td.when(something.fromApi()).thenReturn(1)
  console.log(something.fromApi()) // Just to verify that the replace worked and yes it did

  const result = moduleToTest.get()
  console.log(result) // 0 (but should be 1)

  t.is(result, 1)
})
```

It's of course a very reduced example as the original code is a lot more complex. I'm just wonder if this should theretically work, isn't supported or if there's something I'm doing wrong.

In my real code it could also be broken because I'm inside a pnpm monorepo (uses a lot of links inside node_modules), `something` is actually another package + I'm using exports map inside the `package.json`. A scenario that makes it hard to tell why testdouble is confused.

**Comment by searls** [comment]
@electerious I believe `replaceEsm` works like `replace`, where you have to replace the dependency before you load the subject. (See the [docs](https://github.com/testdouble/testdouble.js/blob/main/docs/7-replacing-dependencies.md#nodejs)). Otherwise the module under test will be loaded (and load its real dependencies) before anything has a chance to offer fake things

So in your case, something like that:

```js
import test from 'ava'
import * as td from 'testdouble'

test('returns 1', async (t) => {
  const something = (await td.replaceEsm('../src/something.js')).default
  const moduleToTest = await import '../src/moduleToTest.js'
  // …
})
```

**Comment by electerious** [comment]
@searls Thanks for the feedback. I will give it a try. I guess it's the following sentence from the docs that confused me:

> As a result, feel free to use td.replaceEsm even after you import the module. This is different from when using td.replace where you must use td.replace first before require-ing your module.

https://github.com/testdouble/testdouble.js/blob/main/docs/7-replacing-dependencies.md#how-module-replacement-works-for-es-modules-using-import

**Comment by searls** [comment]
@electerious apologies i'm not sure how it works because I still haven't had a chance to use it myself -- @giltayar?

**Comment by giltayar** [comment]
Hmmm. It's been a while. Let me check.

**Comment by giltayar** [comment]
OK, I remember. And, yes, that sentence is confusing, and should be changed. What I _meant_ to say that: in CommonJS, once you `require`-ed the module, you stub it by calling `td.replaceCjs` and expect that re-`require` will get the new mocked module. However, with `replaceEsm` you can. So this works in ESM:

```js
await import('foo')
await td.replaceEsm('foo', {fooFunc: stub})
const {fooFunc} = await import('foo')
// fooFunc is now actually "stub"
```

But the same in CJS...

```js
require('foo')
td.replaceCjs('foo', {fooFunc: stub})
const {fooFunc} = require('foo')
// fooFunc is the regular fooFunc, and is not replaced
```

Won't really work. In CJS, once you `require` a module, you can't replace it.

I'll write a PR to fix the documentation.
