### ISSUE TITLE
Remove warning about verifying stubbed functions

### ISSUE THREAD

**Issue by haikyuu** [testdouble/testdouble.js#461]
### Description
The warning explained [here](https://github.com/testdouble/testdouble.js/blob/master/docs/B-frequently-asked-questions.md#why-shouldnt-i-call-both-tdwhen-and-tdverify-for-a-single-interaction-with-a-test-double) should be removed. Let me explain why:

```ts
  const apiRequest = td.function() as () => Promise<number[]>;
  td.when(apiRequest()).thenResolve([1, 2]);
  const result = await useCachedRequest(apiRequest, "req");
  assert.equal(result, [1, 2]);
  td.verify(apiRequest(), { times: 1 });
  const result2 = await useCachedRequest(apiRequest, "req");
  assert.equal(result2, [1, 2]);
  td.verify(apiRequest(), { times: 1 });
```
### Issue

I'm seeing 2 warnings in the console complaining about `verify`. But The calls were justified by the need to count how many times the stubbed function was called.

**Comment by searls** [comment]
In this case, calling verify after you've already verified indirectly via the stubbing is exactly why the warning is in place (because the test wouldn't pass without the stubbing, the additional verification is not necessary as [described in this post](https://blog.testdouble.com/posts/2020-02-25-necessary-and-sufficient/#necessary-tests)).

Usually, ensuring something was called the right number of times is also to overspecify the test by constraining the implementation in ways that aren't necessary. (For example, in no other cases do we test that implementations _don't_ do things we don't want, because there are an infinite number of negatives to prove; would you need a test for a function that adds two numbers to ensure that it doesn't use `+` more times than necessary?).  Nevertheless, if you want to ensure that `apiRequest` was only called a certain number of times, then you can assert that separately by asserting `td.explain(apiRequest).callCount`

**Comment by haikyuu** [comment]
Fair enough. Thanks for the detailed writeup.
