### ISSUE TITLE
--loader=testdouble causes ERR_UNKNOWN_FILE_EXTENSION

### ISSUE THREAD

**Issue by didiercolens** [testdouble/testdouble.js#477]
### Description
If I use the --loader=testdouble with mocha, I get an ERR_UNKNOWN_FILE_EXTENSION as described in https://github.com/nodejs/node/issues/34049. I guess because mocha does not have an extension and testdouble tries to load it somehow?

### Issue

Using any of:
- `node --loader=testdouble ./node_modules/.bin/mocha`
- `NODE_OPTIONS='--loader=testdouble' ./node_modules/.bin/mocha`
- `NODE_OPTIONS='--loader=testdouble' npx mocha`

yields the following error:

```bash
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for /app/node_modules/mocha/bin/mocha
    at new NodeError (internal/errors.js:322:7)
    at defaultGetFormat (internal/modules/esm/get_format.js:71:15)
    at getFormat (file:///app/node_modules/quibble/lib/quibble.mjs:65:12)
    at Loader.getFormat (internal/modules/esm/loader.js:105:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at async Loader.import (internal/modules/esm/loader.js:177:17)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

### Environment

- [x] `node -v` output: v14.18.2
- [x] `npm -v` (or `yarn --version`) output: 6.14.15
- [x] `npm ls testdouble` (or `yarn list testdouble`) version: testdouble@3.16.3

Also tested with:
- [x] `node -v` output: v17.2.0
- [x] `npm -v` (or `yarn --version`) output: 8.1.4
- [x] `npm ls testdouble` (or `yarn list testdouble`) version: testdouble@3.16.3

### Failing Test

- cd empty folder
- npm init
- npm install mocha testdouble -D
- node --loader=testdouble ./node_modules/.bin/mocha

**Comment by searls** [comment]
Hey @giltayar is this related to your work? (I see "loader" and think of you)

**Comment by giltayar** [comment]
Yup, you linked to the right issue. This is a problem in Node.js, and not in `testdouble`. I've never had a problem because I use `mocha --loader=testdouble `, and that works well.

I actually did have a problem, when working on testdouble itself, because the tests there run with another testrunner that is run with just `node` and has no extension, and so I created a "proxy" file with a `.js`  which does a `require("./node_modules/.bin/mocha")` and ran that instead of mocha: https://github.com/testdouble/quibble/blob/dd2b78f21d0aac3ccaada6f8971cf283dbd25f79/package.json#L17
