### ISSUE TITLE
Using td.replaceEsm() in a TypeScript project

### ISSUE THREAD

**Issue by beyerleinf** [testdouble/testdouble.js#480]
### Description
I'm currently trying to use TestDouble to mock dependencies in my TypeScript + ESM project. However, I'm not sure if what I'm trying to accomplish is even possible.

### Issue

Using the `testdouble` loader throws an error when running my tests. Currently both `ts-node/esm` and `testdouble` loader are used in `.mocharc.json` but it also doesn't work with just the `testdouble` loader (see error below) or just the `ts-node/esm` loader (obviously mocking doesn't work). Have I reached the limits of what's possible and need to try and remove the ESM dependencies? Or would I need to ditch TypeScript to make this work?

```
(node:47550) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, getSource
(node:47550) ExperimentalWarning: The Node.js specifier resolution in ESM is experimental.

TypeError: Invalid module "file:///xxxxx/esbuild-azure-functions/src/builder.spec.ts" 
    at new NodeError (node:internal/errors:371:5)
    at ESMLoader.load (node:internal/modules/esm/loader:324:13)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:230:47)
    at link (node:internal/modules/esm/module_job:67:21)
```
### Environment

- [x] `node -v` output: v16.13.1
- [x] `npm -v` output: 8.1.2
- [x] `npm ls testdouble` version: 3.16.4

### Example Repo

You can clone [this repo](https://github.com/beyerleinf/esbuild-azure-functions) and run `npm t` to see the error.

**Comment by searls** [comment]
I need to lean on @giltayar's help to understand this one

**Comment by quinnturner** [comment]
Just chiming in here since I've dealt with this issue as well. From what I gather, there is currently a limitation in Node.js to support more than one loader with ESM in the way that you're describing. It's impossible to use this project in conjunction with `ts-node/esm`. There is active discussion/work going on here: https://github.com/nodejs/loaders.

My personal recommendation is to write tests in JavaScript with `// @ts-check`. If you use a TypeScript monorepo, you can continue to write tests in TypeScript in projects that don't use `testdouble`.

**Comment by searls** [comment]
Ok, we'll all just have to hope for better loader support in Node proper 🤞

**Comment by giltayar** [comment]
I have a solution. But today is a hectic day, so I'll write it down tomorrow. Keep your hopes up high, because at my company we're using both Testdouble _and_ TypeScript.

**Comment by giltayar** [comment]
OK, here goes. You need three loaders! One for TypeScript, one for TestDouble (this one!) and one for supporting multiple loaders because Node.js doesn't support that (yet. work is ongoing to fix this).

*TypeScript*: use https://github.com/giltayar/babel-register-esm to implement TypeScript support. You will need a `babel.config.json` that has the plugin for TypeScript, but, hey, as long as it works! See instructions on how to use this.

*Testdouble*: use the `testdouble` loader for supporting `td.replaceEsm()`.

*Multiple loaders*: use https://github.com/giltayar/esm-multi-loader. See instructions on how to use this to load both the `testdouble` loader and the `babel-register-esm` loader.

Hope this helps..
