### ISSUE TITLE
Get list of mocked modules

### ISSUE THREAD

**Issue by JakobJingleheimer** [testdouble/testdouble.js#519]
I use testdouble pretty extensively, and for each test run, I'd like to list which modules have been replaced (via `replaceEsm`). I don't see anything relevant in the docs or exported from td.

PS Love this lib

**Comment by searls** [comment]
This _may_ be reachable without modification if you want to investigate. I'd look for [references to these values](https://github.com/testdouble/quibble/blob/main/lib/quibble.mjs#L150-L153C10) as a starting point, since they're what gets reset in the ESM loader. (Module replacement is handled by another module we own called [quibble](https://github.com/testdouble/quibble).)

I'd be open to a PR to Quibble and/or testdouble.js itself that provided this information if it's not reachable any other way, because I agree this would be interesting to know from a debugging perspective. However, I've been out of this codebase so long I don't know how much help I'd be. CC/ @giltayar since he was in the quibble code most recently

**Comment by JakobJingleheimer** [comment]
Hmm, it looks like from the code you cited that it does not expose this (that code handles only registration and de-registration of module mocks).

On a related note: I noticed that is using `globalPreload`, which will be removed in node v21 (which is due any day). I believe Gil is aware, but juuust in case.

**Comment by giltayar** [comment]
> On a related note: I noticed that is using globalPreload, which will be removed in node v21 (which is due any day). I believe Gil is aware, but juuust in case.

The current code is an archeological dig that shows _all_ the layers of ESM Loaders, from the first to the last 😁. We currently support Node 16, 18, and 20 (with the new "register"). Which is why we have both `globalPreload` and `initialize`.

I plan on removing all these archeological layers and cleaning up the code once 18 disappears from the map. Till then, `globalPreload` should stay.

**Comment by giltayar** [comment]
> I use testdouble pretty extensively, and for each test run, I'd like to list which modules have been replaced (via replaceEsm). I don't see anything relevant in the docs or exported from td.

We definitely have the information in `quibble`. It's just not exported. It's not trivial, because of the move to off-thread, because the information is in the off-thread loader, but nothing really difficult to work with - a bit of message passing and you're done.

Note that the list of modules will not include their original name (e.g. `lodash`), but rather the final resolved URL (e.g. `file:///.../node_modules/lodash/index.js`).

I can try and do something, but just as a curiosity: why would you need this list?

**Comment by JakobJingleheimer** [comment]
For my immediate need: I have a globally mocked module (which otherwise accesses indexeddb that doesn't exist in node). The module is mocked via mocha's global before/each. In a particular test, it throws that indexeddb doesn't exist, which means something is failing. I want to confirm that testdouble doesn't think it's mocked and hopefully pinpoint why it is not mocked. I suspect it's due to td.reset() in other tests resetting the global mocks (which should never be reset—but the global beforeEach should put them back).

**Comment by giltayar** [comment]
So... For troubleshooting failed tests. Makes a lot of sense.
